### ISSUE TITLE
Adding custom information to powerline

### ISSUE THREAD

**Issue by hoeltgman** [jonathanchu/emacs-powerline#10]
It would be great if it were possible to add further content to the powerline (in a painless way). We can add all sorts of information (time, full path to the current file, etc...) to the standard mode line. For the time being, I don't think this is possible for powerline. If it is, then it must be documented in a better way, as I couldn't find any reference to it.

**Comment by mrvdb** [comment]
I'd like to voice interest in this too. I use jabber extensively with emacs and that has a modeline component to draw my attention. Preferably let powerline use the standard mechanism for custom information in the modeline so all those packages which add bits of info to the mode-line keep working.

**Comment by marcinant** [comment]
I've been trying to extend powerline and add jabber mode-line notifications but unfortunately my lisp skills are too weak.

So, I have to agree with @mrvdb and @hoeltgman. This feature could be very nice and useful.

And more. It could be great to add jabber (and other IM notifications) and mail biff to this powerline only which is on bottom of the Emacs frame (just like notification area).

It could be really great (but I don't know if it is possible at all) with Emacs in full screen mode.

**Comment by rogorido** [comment]
Yes, I also would be interested in this possibility. Above all for the jabber messages. Is there already any work done?

**Comment by rogorido** [comment]
I have created a very simple patch with adds a very very very simple jabber-notification. It is far from perfect, but it seems to work. See http://paste.org/58892

**Comment by jonathanchu** [comment]
Thanks for this Igor.  Let me review this and see what would be a sensible way to incorporate custom info.  A rewrite of this library is definitely in order for it to be able to take in a custom set of powerline modes.  I need to think about what's the best way to do this before commenting further - thanks @hoeltgman @mrvdb @marcinant @rogorido!

**Comment by rogorido** [comment]
thanks. My patch is really primitive and I have a  little problem with the aesthetic. But it works. I'm using every day without problems. Thanks for providing powerline. It is really useful and beautiful!

**Comment by jonathanchu** [comment]
I'm going to hold off on this (as you could already tell by the delay in response) until a better solution is proposed.  There is nothing wrong with @rogorido's solution, I'm just looking for something more modular and easy-to-use for the general public.

Thank you for sharing @rogorido!
