### ISSUE TITLE
powerline breaks which-function-mode

### ISSUE THREAD

**Issue by mgalgs** [jonathanchu/emacs-powerline#17]
[`which-function-mode`](http://www.gnu.org/software/emacs/manual/html_node/emacs/Which-Function.html) doesn't work when I have powerline enabled...

Any ideas why that is?

**Comment by jonathanchu** [comment]
My sincere apologies on the delay in response.  If this is still relevant to you, I'd like to help - if not, please disregard :stuck_out_tongue: 

As of now, v24.4 seems to activate `which-function-mode` correctly.  Do you still have this issue?

**Comment by mgalgs** [comment]
Not affecting me anymore. Thanks!
