### ISSUE TITLE
powerline-make-fill

### ISSUE THREAD

**Issue by rougier** [jonathanchu/emacs-powerline#2]
This function did not work quite right for me( emacs 23.3.1/OSX), I had to replace with:

(defun powerline-make-fill
  (color)
  ;; justify right by filling with spaces to right fringe, 20 should be calculated
  (let ((plface (powerline-make-face color)))
    (propertize " " 'display '((space :align-to (- right-margin 20)))
                'face plface)))

I use margin instead of fringe that saved the test against the scrollbar.

**Comment by jonathanchu** [comment]
Closing as this is an old issue - @rougier if this is still an issue in emacs v24.x, please do re-open.  This should be OK now though.
