### ISSUE TITLE
Why `(scroll-bar-mode -1)` ?

### ISSUE THREAD

**Issue by Silex** [jonathanchu/emacs-powerline#24]
Why do you need this? As a result I have to load the package first AND THEN enable scroll bar mode to have them, because your package removes them unconditionnaly.

**Comment by jonathanchu** [comment]
Good catch, this was a remnant from testing against older versions of emacs.  I can make this fix easily, but perhaps you want to make a PR and I'll merge (and add you to AUTHORS list) ? :smile: :+1:

**Comment by Silex** [comment]
Done :)
