### ISSUE TITLE
Inactive faces not applied

### ISSUE THREAD

**Issue by LouisKottmann** [jonathanchu/emacs-powerline#26]
Nevermind, I was using milkypostman's version. Disregard issue.

**Comment by jonathanchu** [comment]
Hehe, not a problem at all!  @milkypostman and I ought to combine the good bits and consolidate this project!  :smile: :+1:

**Comment by milkypostman** [comment]
That would be good. I haven't really felt motivated with this project anymore so mine is kinda falling apart.  Should I switch over the MELPA recipe to yours?

**Comment by jonathanchu** [comment]
@milkypostman I would say no, not yet at least - keep yours up for those that are using it and depend on it.  

I'll go through our versions this weekend and write up some quick notes on how I think we should proceed and send them over to you to review for your input.  I think we can make this pretty painless :smile_cat:

**Comment by jonathanchu** [comment]
Thanks @milkypostman!
