### ISSUE TITLE
icons for git repos (question)

### ISSUE THREAD

**Issue by VdeVatman** [jonathanchu/emacs-powerline#32]
Is there any chance to show the git icons for files within a git repo instead of 'Git' in Git:<branch-name>? as it happens in vim-powerline.

**Comment by jonathanchu** [comment]
Hey @VdeVatman!  Sorry for any confusion, but please check out the awesome @milkypostman's [powerline](https://github.com/milkypostman/powerline), as this is the version that's currently on MELPA (if that's where you installed powerline from).  Mine is from the dark days before that and this repo is really not supported anymore.

And last I saw in that codebase, I believe there were customizations that you can do in it, so it may address your question.

Cheers :beers:
