### ISSUE TITLE
Symbols not showing up correctly

### ISSUE THREAD

**Issue by meain** [jonathanchu/emacs-powerline#33]
The symbols does not show up like in the screenshot in readme, its kinda messed up.

`arrow14`
![img-arrow14](http://i.imgur.com/U2HpJeM.png)
`curve`
![img-curve](http://i.imgur.com/MvP3PjX.png)

**Comment by jerrykal** [comment]
I have same issue too.

**Comment by jerrykal** [comment]
paste this in your init file 
(set-face-attribute 'default nil :height 100)
The value is in 1/10pt, so 100 will give you 10pt.

**Comment by meain** [comment]
Thanks, it works
