### ISSUE TITLE
Blank modeline with display-time-mode

### ISSUE THREAD

**Issue by alinnow** [jonathanchu/emacs-powerline#4]
I tried to install powerline, but when I `(require 'powerline)`, I just get a blank green modeline of the same height as the normal one.
In `*Messages*`, I see

> Error during redisplay: (wrong-type-argument stringp ("" display-time-string)) [3 times]

I tried `(setq debug-on-error t)`, but no errors were raised

Disabling `display-time-mode` does not help, even when done before calling `(require 'powerline)` for the first time in a session. The only workaround is to remove `(display-time-mode t)` from my init file. I'm okay with ceasing my use of`display-time-mode`, but I thought I'd post this bug incase it affects other people.

If you need some more info, let me know!

Tested Emacs/OS versions:

> GNU Emacs 24.1.50.1 (amd64-unknown-freebsd9.0, GTK+ Version 3.0.12)
> GNU Emacs 24.0.92.1 (i386-mingw-nt6.1.7601)

**Comment by jonathanchu** [comment]
Thanks, this is great detail and very helpful.  Looking into this now if I can work time-mode into this without messing up anything else.

**Comment by jonathanchu** [comment]
global-mode-string seemed to be the culprit.  I removed it as it wasn't really being used anyway.  Tested with (display-time-mode 1) and it rendered correctly.

https://github.com/jonathanchu/emacs-powerline/commit/4f04dbd3b2829da978cc986abdb525b542688655

Let me know if this worked for you.

**Comment by alinnow** [comment]
This fixes the blank modeline, however `display-time-mode` doesn't appear to add anything to the powerline.

Not a huge issue for me, but it would be great if powerline supported all the standard modeline additions.

**Comment by jonathanchu** [comment]
You bring up a good point - the main issue is that there isn't a way to customize this without forking and modifying powerline.el.  I need to think about how to extend this to make it more customizable in the future, and your issue brings that to light that it will be needed sooner than later. :smiley:

**Comment by jonathanchu** [comment]
This should have been fixed in @zarkone's [pull request](https://github.com/jonathanchu/emacs-powerline/issues/27) merged into `master` already.  If this is still an issue for you, please do give this a try and see if it solves it for you @alanpearce.  Thanks and apologies on the delays in response :beers:
