### ISSUE TITLE
Opening a scheme-file/loading scheme-mode leads to blank powerline.

### ISSUE THREAD

**Issue by christianlask** [jonathanchu/emacs-powerline#5]
When I open a file that loads scheme-mode (like .ss or .scm), I get an empty green powerline. This happens, too, when I open a file and load scheme-mode manually afterwards.

**Comment by jonathanchu** [comment]
Thanks for this - what version of emacs are you running?

**Comment by christianlask** [comment]
I'm sorry, should've mentioned this right away ;) I'm running Emacs 24.0.97.1.

**Comment by jonathanchu** [comment]
Thanks!  I was able to reproduce this easily.  Found out that mode-line-process was causing the display issue.  This commit seems to fix it:

https://github.com/jonathanchu/emacs-powerline/commit/2501d122568ad3941da5b8d619ba4b669159df14

It's updated in `master` now, so you can pull directly from it.  Let me know if this worked for you.

**Comment by christianlask** [comment]
Thank you very much. :) My emacs is very good looking now.

**Comment by jonathanchu** [comment]
:smile: :thumbsup: :cake:
