### ISSUE TITLE
html-mode makes powerline blank

### ISSUE THREAD

**Issue by christianlask** [jonathanchu/emacs-powerline#7]
When I open a file that makes emacs load `html-mode`, the powerline goes blank. The same happens, when I create a new file and load `html-mode` manually.

**Comment by jonathanchu** [comment]
What version of emacs are you using when this happens?

**Comment by jonathanchu** [comment]
Oh, sorry - just saw the other issue where you listed the info (v24.0.97.1).  I'll take a look - thanks!

**Comment by christianlask** [comment]
Oh, and I forgot again to mention my Emacs version ;) Sorry about that.

**Comment by gsmnv** [comment]
I have same issue.
Version: GNU Emacs 24.1.1

**Comment by filsinger** [comment]
Same issue here.
GNU Emacs 24.1.1 (x86_64-apple-darwin, NS apple-appkit-1038.36) of 2012-06-10

**Comment by gsmnv** [comment]
-(defpowerline major-mode  (propertize mode-name
+(defpowerline major-mode  (propertize (format-mode-line mode-name)
Fixes problem.

**Comment by christianlask** [comment]
Can confirm the fix. Thank you!

**Comment by jonathanchu** [comment]
Thanks @Okasu!  I'll add this in shortly.

**Comment by jonathanchu** [comment]
Thanks again! https://github.com/jonathanchu/emacs-powerline/commit/6db27626e0d5d79d1854c346744f344eec4abc80
